development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: inventory_development
  pool: 5
  username: user
  password: user
  host: db-service # For kubernetes. This is the name of the service behind which the pod is running that hosts the container running this app.
  socket: '/tmp/mysql.sock'

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: inventory_test
  pool: 5
  username: user
  password: user
  host: db-service # For kubernetes. This is the name of the service behind which the pod is running that hosts the container running this app.
  socket: '/tmp/mysql.sock'
